apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-scheduler
    app.kubernetes.io/name: kube-scheduler
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: https-metrics
      port: 10259
      targetPort: 10259
      protocol: TCP
  selector:
    component: kube-scheduler